Repository nissy-dev/swc-plugin-react-native-web, pull requests merged in 2022-10, with the labels that each got.

#24 Update swc dependencies for next 12.3.2
  Cargo.lock
  Cargo.toml
  example/package-lock.json
  example/package.json
  package.json
  src/lib.rs
  src/utils/export_decl_visitor_utils.rs
  src/utils/import_decl_visitor_utils.rs
Labels: bug

#25 chore: update github actions
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: refactor

#27 fix: support next.js 12.3.1
  Cargo.lock
  Cargo.toml
  example/package-lock.json
  example/package.json
  package.json
  src/utils/export_decl_visitor_utils.rs
  src/utils/import_decl_visitor_utils.rs
Labels: bug

#26 Update get_dist_location.rs
  src/utils/get_dist_location.rs
Labels: bug

#28 chore: update plugin version in example
  example/package-lock.json
  example/package.json
Labels: refactor

#29 fix: support Next.js 13
  Cargo.lock
  Cargo.toml
  example/package-lock.json
  example/package.json
  package.json
  src/utils/export_decl_visitor_utils.rs
  src/utils/import_decl_visitor_utils.rs
Labels: bug

#30 chore: update plugin version
  example/package-lock.json
  example/package.json
Labels: chore
